### ISSUE TITLE
Remote debugging

### ISSUE THREAD

**Issue by asebak** [fioan89/sourcesync#17]
Does anyone know how to do remote debugging using sourcesync?

**Comment by fioan89** [comment]
Remote debugging?? I'm not sure I entirely understand your question. But I can say this:
If you want to remote debug java code the community edition of IntelliJ offers support for this. Just google  it. Now if you refer to python code - than I'm afraid this is a little harder. The community edition does not offer support for remote debugging. Only the pro edition. Probably you will find more info on this (and maybe workarounds) on google. Anyway this issue is not really a something that has to do with sourcesync which is just a file transfer plugin. :) Can we close this issue?

**Comment by asebak** [comment]
ok
